package xyz.qmc.client;

import java.io.ByteArrayOutputStream;
import java.io.IOException;
import java.io.RandomAccessFile;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.zip.DeflaterOutputStream;

/** Writes the stable Anvil container; chunk NBT itself is generated by Minecraft. */
final class RegionWriter implements AutoCloseable {
	private static final int SECTOR = 4096;
	private final RandomAccessFile file;
	private final int[] locations = new int[1024];
	private int nextSector;

	RegionWriter(Path path) throws IOException {
		Files.createDirectories(path.getParent());
		file = new RandomAccessFile(path.toFile(), "rw");
		if (file.length() < SECTOR * 2L) file.setLength(SECTOR * 2L);
		file.seek(0); nextSector = 2;
		for (int i = 0; i < locations.length; i++) { locations[i] = file.readInt(); nextSector = Math.max(nextSector, (locations[i] >>> 8) + (locations[i] & 255)); }
	}

	synchronized void write(int chunkX, int chunkZ, byte[] raw) throws IOException {
		byte[] compressed;
		try (ByteArrayOutputStream bytes = new ByteArrayOutputStream(); DeflaterOutputStream zip = new DeflaterOutputStream(bytes)) {
			zip.write(raw); zip.finish(); compressed = bytes.toByteArray();
		}
		int sectors = (compressed.length + 5 + SECTOR - 1) / SECTOR;
		if (sectors > 255) throw new IOException("Chunk is too large for Anvil: " + chunkX + "," + chunkZ);
		int index = (chunkX & 31) + (chunkZ & 31) * 32;
		int old = locations[index], oldOffset = old >>> 8, oldSectors = old & 255;
		int offset = oldOffset != 0 && oldSectors >= sectors ? oldOffset : nextSector;
		if (offset == nextSector) nextSector += sectors;
		long position = (long) offset * SECTOR;
		file.seek(position); file.writeInt(compressed.length + 1); file.writeByte(2); file.write(compressed);
		file.seek(position + (long) sectors * SECTOR - 1); file.write(0);
		locations[index] = (offset << 8) | sectors;
		file.seek(index * 4L); file.writeInt(locations[index]);
		file.seek(SECTOR + index * 4L); file.writeInt((int) (System.currentTimeMillis() / 1000));
	}
	@Override public synchronized void close() throws IOException { file.close(); }
}
